In [1]:
# day 8
f = open("data/data08.txt", "r")
lines = f.readlines()
lines = [l[:-1] for l in lines]
#lines = ['30373', '25512', '65332', '33549', '35390']
print(lines[:5])

['101232232424431123432342554040352101405502025646520640026102435415402415524241404341001022013221221', '322003200404313034023203145443134010555246652210042156042654635314322525041550121322403330300102030', '300223331202022110511510154103110142442012332003514242206354525511353252421542430110200442102312123', '323133401312301310040251134225352136126616004434252462045055305202261355433025233042244241414400023', '101104403040123044220034201231621525016350121330311611014454116414515052210415423202213344444213032']


In [2]:
import numpy as np
N = len(lines)
A = np.zeros((N, N), np.int8)
for i, line in enumerate(lines):
    for j, s in enumerate(line):
        A[i, j] = int(s)
print(A)

[[1 0 1 ... 2 2 1]
 [3 2 2 ... 0 3 0]
 [3 0 0 ... 1 2 3]
 ...
 [0 2 0 ... 0 1 2]
 [0 0 3 ... 3 3 2]
 [2 2 3 ... 0 3 3]]


In [3]:
k = 4*N-4
L = []

for i in range(1, N-1):
    for j in range(1, N-1):
        a = A[i, j]
        if a > np.max(A[:i, j]):
            k += 1
            L.append((i,j))
        elif a > np.max(A[i+1:, j]):
            k += 1
            L.append((i,j))
        elif a > np.max(A[i, :j]):
            k += 1
            L.append((i,j))
        elif a > np.max(A[i, j+1:]):
            k += 1
            L.append((i,j))
print(k)

1690


In [4]:
B = np.zeros((N, N), np.int64)

for i in range(1, N-1):
    for j in range(1, N-1):
        a = A[i, j]
        kN, kS, kW, kE = 1, 1, 1, 1
        
        ii = i+1
        while A[ii, j]<a:
            ii += 1 
            if ii==N:
                break
            kS += 1
        ii = i-1
        while A[ii, j]<a:
            ii -= 1
            if ii<0:
                break
            kN += 1
        jj = j+1
        while A[i, jj]<a:
            jj += 1
            if jj==N:
                break
            kE += 1
        jj = j-1
        while A[i, jj]<a:
            jj -= 1
            if jj<0:
                break
            kW += 1
        B[i, j] = kN * kS * kW * kE
        if B[i, j]<0:
            print(i,j)
            print(kN, kS, kW, kE)
print(B.max())

535680


In [5]:
B[2:5, 4:7]

array([[  2,   5,   2],
       [ 12,   1, 234],
       [  1,  60,  16]], dtype=int64)