In [1]:
# day12
import numpy as np
import heapq
from warnings import warn

f = open("data/data12.txt", "r")
lines = f.readlines()
lines = [l[:-1] for l in lines]
n, m = len(lines), len(lines[0])
A = np.zeros((n, m))

for i, line in enumerate(lines):
    for j, s in enumerate(line):
        if s == 'S':
            A[i, j] = 1
            start = (i, j)
        elif s == 'E':
            A[i, j] = 26
            end = (i, j)
        else:
            A[i, j] = ord(s) - 96
    
print(A)
print(start, end)

[[1. 2. 1. ... 1. 1. 1.]
 [1. 2. 1. ... 1. 1. 1.]
 [1. 2. 1. ... 1. 1. 1.]
 ...
 [1. 2. 3. ... 1. 1. 1.]
 [1. 2. 3. ... 1. 1. 1.]
 [1. 2. 3. ... 1. 1. 1.]]
(20, 0) (20, 68)


In [2]:
# adjacency matrix
mat = []
for i in range(n):
    for j in range(m):
        pos = i*m + j
        val = A[i, j]
        adj = []
        #top
        if(i>0 and val - A[i-1, j] < 2):
            adj.append(j + (i-1)*m)
        #left
        if(j>0 and val - A[i, j-1] < 2):
            adj.append(j-1 + i*m)
        #down
        if(i+1<n and val - A[i+1, j] < 2):
            adj.append(j + (i+1)*m)
        #right
        if(j+1<m and val - A[i, j+1] < 2):
            adj.append(j+1 + i*m)
        mat.append(adj)

def dijkstra(start, mat, cost):
    q = []
    cost[start] = 0 
    q.append((start, 0))
    while len(q)>0:
        node,c = q.pop() #node, cost
        if cost[node] != c:
            continue #already found a better path for n
        for v in mat[node]:
            if(cost[v] > (c+1)):
                cost[v]=c+1
                q.append((v,c+1))

cost = [999] * (m * n)
dijkstra(end[0]*m + end[1], mat, cost)
cost[start[0]*m + start[1]]

412

In [3]:
min([cost[i*m+j] for i in range(n) for j in range(m) if A[i, j]==1])

402